### ISSUE TITLE
ISCSI.Login returns wrong error codes.

### ISSUE THREAD

**Issue by mvollmer** [storaged-project/storaged#30] opened 2015-10-09 09:20 UTC
Trying to log in with wrong creds yields just org.storaged.Storaged.Error.Failed instead of the expected org.storaged.Storaged.Error.ISCSI.LoginAuthFailed.

The reason seems to be that libiscsi_node_login returns a (pretty useless) errno code for ENOTCONN == 107 for any failure.

**Comment by phatina** [comment] 2015-10-13 09:01
This requires [open-iscsi](https://github.com/phatina/open-iscsi) to be slightly redesigned, because the libiscsi hides the actuall error codes returned from `libiscsi_*` calls.

**Comment by phatina** [comment] 2015-10-27 08:17
Fixes for this issue can be found in my [open-iscsi repo](https://github.com/phatina/open-iscsi), fow now. See commits [739e31a](https://github.com/phatina/open-iscsi/commit/739e31a605e723c18f306e60c070f3ea9f6b748e) and [8ee02da](https://github.com/phatina/open-iscsi/commit/8ee02da1aac137226928a24445017c921d54f201).

**Note:** I'll try my best to propagate these changes into upstream repo and Fedora.

**Comment by phatina** [comment] 2015-10-27 08:21
Closing since, Storaged doesn't require any modifications to pick up the proper error codes. The problem is/was in [open-iscsi](https://github.com/phatina/open-iscsi).

**Closed by phatina** 2015-10-27 08:21 UTC
Labels: bug, wontfix
